import fetch from 'node-fetch'
import { extractTextFromImage } from './ocrService.js'

const OLLAMA_URL = 'http://localhost:11434/api/generate'
const MODEL = 'mistral'

/**
 * Comprehensive fake content detection using AI
 * Checks for: fake news, misleading information, AI-generated content, deepfakes
 * 
 * @param {string} textContent - The text content of the post
 * @param {Array} mediaFiles - Array of media file objects with _localPath and _mimeType
 * @returns {Promise<{verdict: string, score: number, reason: string, isAIGenerated: boolean}>}
 */
export const detectFakeContent = async (textContent = '', mediaFiles = []) => {
  try {
    let extractedImageText = ''
    let combinedAnalysis = {
      isFake: false,
      isMisleading: false,
      isAIGenerated: false,
      confidence: 0,
      reasons: []
    }

    // Extract text from images (if any) to get more context
    if (mediaFiles.length > 0) {
      for (const media of mediaFiles) {
        if (media._mimeType?.startsWith('image/')) {
          try {
            const imageText = await extractTextFromImage(media._localPath)
            if (imageText) {
              extractedImageText += (extractedImageText ? ' | ' : '') + imageText
            }
          } catch (err) {
                      }
        }
      }
    }

    // Combine text content and extracted image text
    const fullText = [textContent, extractedImageText].filter(Boolean).join('\n\nExtracted from images:\n')
    
    if (!fullText.trim()) {
            return { 
        verdict: 'safe', 
        score: 0, 
        reason: 'No text content to analyze', 
        isAIGenerated: false 
      }
    }

    // Run comprehensive AI analysis
    const prompt = `You are an advanced content moderation AI. Your job is to detect fake news, misleading information, and AI-generated content.

Analyze the following post content:
"${fullText}"

Respond in this exact JSON format (no extra text, just JSON):
{
  "isFake": true or false,
  "isMisleading": true or false,
  "isAIGenerated": true or false,
  "confidence": a number between 0 and 1,
  "reasoning": "detailed explanation of why you flagged this content"
}

Detection Criteria:
1. FAKE NEWS: False claims, fabricated events, manipulated facts, conspiracy theories without evidence
2. MISLEADING: Deceptive headlines, out-of-context information, cherry-picked data, half-truths
3. AI-GENERATED: Content that appears to be generated by AI (unnatural phrasing, repetitive patterns, generic language)

Rules:
- isFake = true ONLY if content contains demonstrably false information (high confidence: >0.85)
- isMisleading = true if content is deceptive, manipulative, or presents partial truth in a misleading way (confidence: >0.75)
- isAIGenerated = true if content shows strong signs of AI generation (confidence: >0.7)
- Be conservative: only flag with high confidence
- Provide specific reasoning for your decision
- If uncertain, set all flags to false and explain why`

    const response = await fetch(OLLAMA_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: MODEL,
        prompt,
        stream: false,
        options: {
          temperature: 0.1, // very low temp for accurate detection
          num_predict: 250
        }
      })
    })

    if (!response.ok) {
      throw new Error(`Ollama responded with status ${response.status}`)
    }

    const data = await response.json()
    const rawText = data.response?.trim() || ''

    // Extract JSON from the response
    const jsonMatch = rawText.match(/\{[\s\S]*\}/)
    if (!jsonMatch) {
            return { 
        verdict: 'safe', 
        score: 0, 
        reason: 'Could not parse AI response', 
        isAIGenerated: false 
      }
    }

    const parsed = JSON.parse(jsonMatch[0])
    combinedAnalysis = parsed

    // Determine final verdict based on flags and confidence
    let verdict = 'safe'
    let score = parsed.confidence || 0
    let reason = parsed.reasoning || 'No issues detected'

    // IMMEDIATE REJECTION: High-confidence fake news
    if (parsed.isFake && parsed.confidence >= 0.85) {
      verdict = 'fake'
      reason = `FAKE NEWS DETECTED: ${parsed.reasoning}`
      console.log(`[FakeContentDetector] ❌ REJECTING - Fake news detected with ${(score * 100).toFixed(0)}% confidence`)
    }
    // IMMEDIATE REJECTION: High-confidence misleading content
    else if (parsed.isMisleading && parsed.confidence >= 0.80) {
      verdict = 'fake'
      reason = `MISLEADING CONTENT DETECTED: ${parsed.reasoning}`
      console.log(`[FakeContentDetector] ❌ REJECTING - Misleading content detected with ${(score * 100).toFixed(0)}% confidence`)
    }
    // SEND TO REVIEWERS: Moderate confidence fake/misleading
    else if ((parsed.isFake || parsed.isMisleading) && parsed.confidence >= 0.60) {
      verdict = 'suspicious'
      reason = `SUSPICIOUS CONTENT: ${parsed.reasoning}`
          }
    // AI-GENERATED: Flag but don't auto-reject (let reviewers decide)
    else if (parsed.isAIGenerated && parsed.confidence >= 0.70) {
      verdict = 'suspicious'
      reason = `AI-GENERATED CONTENT SUSPECTED: ${parsed.reasoning}`
          }
    else {
          }

    return {
      verdict,
      score,
      reason,
      isAIGenerated: parsed.isAIGenerated || false,
      isFake: parsed.isFake || false,
      isMisleading: parsed.isMisleading || false
    }

  } catch (err) {
    console.error('[FakeContentDetector] ⚠️  FALLBACK TRIGGERED:', {
      error: err.message,
      note: 'Ollama is likely not running on http://localhost:11434',
      recommendation: 'Install Ollama and run: ollama run mistral'
    })
    
    // TEMPORARY FALLBACK: Use keyword-based detection
    const isSuspicious = quickFakeCheck(fullText)
    
    if (isSuspicious) {
      return { 
        verdict: 'suspicious', 
        score: 0.6, 
        reason: 'Suspicious keywords detected (Ollama unavailable - keyword-based fallback)', 
        isAIGenerated: false 
      }
    }
    
    // Default fallback: send to reviewers for manual review
    // This ensures nothing bypasses human oversight
    return { 
      verdict: 'suspicious', 
      score: 0.3,
      reason: `AI Detection unavailable (${err.message}) - sent to reviewers for manual verification`, 
      isAIGenerated: false 
    }
  }
}

/**
 * Quick keyword-based fake content check (used as fallback)
 * 
 * @param {string} content - Post text content
 * @returns {boolean} - True if content contains suspicious keywords
 */
export const quickFakeCheck = (content = '') => {
  const text = content.toLowerCase()
  
  // Common fake news red flags
  const redFlags = [
    /\bbreaking\b.*\bshocking\b/,
    /\bthey don'?t want you to know\b/,
    /\b100% proven\b/,
    /\bdoctors hate\b/,
    /\bclick here to\b/,
    /\bshare if you agree\b/,
    /\bgovernment is hiding\b/,
    /\bsecret cure\b/,
    /\bmainstream media won'?t tell you\b/,
  ]
  
  return redFlags.some(pattern => pattern.test(text))
}

